version: 2.1
orbs:
  job-queue: tkoft/job-queue@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      - orb-tools/pack:
          filters: *filters
      - hold:
          type: approval
          requires: [orb-tools/pack]
      - job-queue/queue:
          filters:
            tags:
              ignore: /.*/
          context: orb-publishing
          requires: [hold]
      - orb-tools/publish:
          orb-name: tkoft/job-queue
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - job-queue/queue
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
